name: aaab
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.0.1
  auto_route: ^5.0.4
  get_it: ^7.2.0
  injectable: ^2.1.0
  logger: ^1.1.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.1
  firebase_storage: ^11.0.8
  http: ^0.13.5
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  bottom_navy_bar: ^6.0.0
  intl: ^0.17.0
  open_mail_app: ^0.4.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_svg: ^1.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/
#
# Fonts Example
#  fonts:
#    - family: Open Sans
#      fonts:
#        - asset: assets/fonts/OpenSans-Italic.ttf
#          style: italic
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/OpenSans-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/OpenSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/OpenSans-Regular.ttf
#          weight: 400
