name: aaab
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.0.1
  auto_route: ^5.0.4
  get_it: ^7.1.3
  injectable: ^2.1.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.3
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
# Assets Example
#  assets:
#    - assets/images/
#
# Fonts Example
#  fonts:
#    - family: Open Sans
#      fonts:
#        - asset: assets/fonts/OpenSans-Italic.ttf
#          style: italic
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/OpenSans-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/OpenSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/OpenSans-Regular.ttf
#          weight: 400
